Numpy - NumPy is also called as Numerical Python, it is an universal library for working with numerical data. It is an open source library almost used in every field of Science and Engineering.
- Beginner to Experiensed brings NumPy in use for different scientific researches and so on.
- The NumPy API is used extensively in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.
- NumPy Libraries includes multidimensional array and Matrices data structures
- NumPy is used to perform different mathematical calculations.
- It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it.

Array - An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element.
- The rank of the array is the number of dimensions.
- The shape of the array is a tuple of integers giving the size of the array along each dimension.

In [3]:
import numpy as np

In [6]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [9]:
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
#indexing in array starts with 0

In [13]:
print(a[0])

[1 2 3 4]


1D array, 2D array, ndarray, vector, matrix

The NumPy ndarray class is used to represent both matrices and vectors.
- Vector - is an array with a single dimension (there’s no difference between row and column vectors)
- Matrix - refers to an array with two dimensions.
- Tensor - 3-D or higher dimensional arrays

- Axes - means dimensions

In [14]:
#Creating an array

In [15]:
arr = ([1,2,3,4])
arr

[1, 2, 3, 4]

In [16]:
#an array filled with zero's

In [17]:
arr = np.zeros(2)

In [18]:
arr

array([0., 0.])

In [19]:
#an array filled with one's 

In [21]:
arr = np.ones(2)

In [22]:
arr

array([1., 1.])

In [23]:
#Creating an empty array

In [33]:
np.empty(1) #may vary

array([1.27319747e-313])

In [34]:
np.arange(4) #using range 

array([0, 1, 2, 3])

In [35]:
#using linspace() for creating an array 

In [4]:
np.linspace(1, 6, num = 10) # an array is created with 
#linerarly spaced at specific intervls 

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [38]:
#Explicietly typecasting the array from np.float64 to np.int64

In [39]:
np.ones(2) #float as default 

array([1., 1.])

In [40]:
np.ones(2, dtype = np.int64) #explicit typecasting

array([1, 1], dtype=int64)

Adding, removing, and sorting elements

In [41]:
#Sorting an element is simple with np.sort().

In [42]:
arr = np.array([1,2,8,6,5,4,9])
np.short(arr)

array([1, 2, 8, 6, 5, 4, 9], dtype=int16)

In [45]:
a = np.array([12,34,56,34])
b = np.array([13,14,89,90])
np.concatenate((a,b))

array([12, 34, 56, 34, 13, 14, 89, 90], dtype=int16)

In [51]:
x = np.array([[12,3,4,5,6],[2,4,5,1,7]])
y = np.array([[1,4,5,6,2]])
np.concatenate((x,y), axis = 0)

array([[12,  3,  4,  5,  6],
       [ 2,  4,  5,  1,  7],
       [ 1,  4,  5,  6,  2]])

How do you know the shape and size of an array?

- ndarray.ndim - will tell you the number of axes, or dimensions, of the array.
- ndarray.size - will tell you the total number of elements of the array.
- ndarray.shape - will display a tuple of integers that indicate the number of elements stored along each dimension of the array. 

In [56]:
arr = np.array([[[2,4,5], [3,4,5]], [[3,4,5],[3,6,3]], [[6,7,8],[2,7,4]], [[6,7,8],[2,7,4]]])
arr.ndim #the number of dimensions of the array

3

In [57]:
arr.size #total number of element

24

In [58]:
arr.shape

(4, 2, 3)

How to convert a 1D array into a 2D array
- np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [63]:
arr2 = arr[np.newaxis,:]
arr2

array([[[[2, 4, 5],
         [3, 4, 5]],

        [[3, 4, 5],
         [3, 6, 3]],

        [[6, 7, 8],
         [2, 7, 4]],

        [[6, 7, 8],
         [2, 7, 4]]]])

In [64]:
arr2.shape

(1, 4, 2, 3)

In [65]:
arr.shape

(4, 2, 3)

In [68]:
arr3 = arr[: , np.newaxis]
arr3.shape

(4, 1, 2, 3)